### ISSUE TITLE
Inference for larger molecule

### ISSUE THREAD

**Issue by Barry0121** [THUNLP-MT/PepGLAD#7]
Hi, 

I'm test PepGLAD on producing larger peptides. I see in the paper the size distribution of the training dataset maxed out around 50 residues. However, when I tested the provided example with a modified max_length parameter, I get an CUDA error. Not sure if this is related to Out-of-Memory, but I'm already using a GPU with around 80GBs of memory. 

Here's my test command: 
```
CUDA_VISIBLE_DEVICES=0 python -m api.run     --mode codesign     --pdb assets/1ssc_A_B.pdb     --pocket assets/1ssc_A_pocket.json     --out_dir ./output/codesign     --length_min 8     --length_max 50     --n_samples 10
```

Here's the error: 
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/data/PepGLAD/api/run.py", line 264, in <module>
    design(
  File "/home/data/PepGLAD/api/run.py", line 193, in design
    batch_X, batch_S, batch_pmetric = model.sample(
                                      ^^^^^^^^^^^^^
  File "/root/miniconda3/envs/PepGLAD/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/data/PepGLAD/models/LDM/ldm.py", line 170, in sample
    H_0 = self.hidden2latent(H_0)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/PepGLAD/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/PepGLAD/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/PepGLAD/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 125, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
```

Please advise, thank you.

**Comment by kxz18** [comment]
Hi, thanks for your interest in our work! I think there might be two possible reasons:

1. For peptide longer than 25 residues, the [checkpoint trained on PepBDB](https://github.com/THUNLP-MT/PepGLAD/releases/tag/v1.0) might be required as the default checkpoint is trained on pepbench, which only include peptides shorter than 25 residues. Currently the path of the checkpoint is hard-coded [here](https://github.com/THUNLP-MT/PepGLAD/blob/2474da017cc6c7341e3472c7cf7d2922511f76d6/api/run.py#L261), so you might need to revise it directly in the python script. However, I think I should mention that I feel there might be some data quality problem related to PepBDB as the model trained on it often generates weird results with broken or twisted chains. As far as I know, in addition to our PepGLAD, recent works like PepFlow and DiffPepBuilder all filter data from PDB directly instead of using PepBDB.

2. The cuda error seems to be related to the environment. There might be some mismatch between the pytorch, cuda, and cudnn versions.

**Comment by Barry0121** [comment]
Thank you for the explanation! 

I want to try the PepBDB checkpoint, but in `checkpoint.zip` only contain the `codesign.ckpt` and `fixseq.ckpt`. I don't see the `codesign_pepbdb.ckpt` there. 

Can you share that too? Thanks.

**Comment by kxz18** [comment]
Can you try the zip file at this [url](https://github.com/THUNLP-MT/PepGLAD/releases/download/v1.0/checkpoints.zip)? I think I just uploaded the PepBDB checkpoints recently.

**Comment by Barry0121** [comment]
Yep, the files here worked! It also fixed the CUBLAS errors as well, which I'm not entirely sure how...

Thanks a lot!
